// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH_dh6HltB3xpyKYJYhc-jgMGHMFd4pi8',
    appId: '1:406417088465:web:2b542cc8143d1247598af0',
    messagingSenderId: '406417088465',
    projectId: 'flutter-chat-app-d1d32',
    authDomain: 'flutter-chat-app-d1d32.firebaseapp.com',
    storageBucket: 'flutter-chat-app-d1d32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBms5ybVsSDmd4a3rp3RDuEtPRI9NRifWo',
    appId: '1:406417088465:android:530824656cfc422f598af0',
    messagingSenderId: '406417088465',
    projectId: 'flutter-chat-app-d1d32',
    storageBucket: 'flutter-chat-app-d1d32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqh_OfcOEgB4YGQRhgbi_MN1N-In8CGFw',
    appId: '1:406417088465:ios:f889fbd2657b1657598af0',
    messagingSenderId: '406417088465',
    projectId: 'flutter-chat-app-d1d32',
    storageBucket: 'flutter-chat-app-d1d32.firebasestorage.app',
    iosBundleId: 'com.example.courseProject7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqh_OfcOEgB4YGQRhgbi_MN1N-In8CGFw',
    appId: '1:406417088465:ios:f889fbd2657b1657598af0',
    messagingSenderId: '406417088465',
    projectId: 'flutter-chat-app-d1d32',
    storageBucket: 'flutter-chat-app-d1d32.firebasestorage.app',
    iosBundleId: 'com.example.courseProject7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH_dh6HltB3xpyKYJYhc-jgMGHMFd4pi8',
    appId: '1:406417088465:web:486637d7f02c94a5598af0',
    messagingSenderId: '406417088465',
    projectId: 'flutter-chat-app-d1d32',
    authDomain: 'flutter-chat-app-d1d32.firebaseapp.com',
    storageBucket: 'flutter-chat-app-d1d32.firebasestorage.app',
  );

}